<?php


$color_schemes=[
    'default' => [
      'title' => t('Default'),
      'colors' => [
      'Primary Color' => '#08387f',
      'Secondary Color' => '#29b6ff',
      ],
    ],
    'set_1' => [
      'title' => t('Color Set 1'),
      'colors' => [
      'Primary Color' => '#7ba021',
      'Secondary Color' => '#d0e431',
      ],
    ],
    'set_2' => [
      'title' => t('Color Set 2'),
      'colors' => [
      'Primary Color' => '#a24077',
      'Secondary Color' => '#f783bd',
      ],
    ],
    'set_3' => [
      'title' => t('Color Set 3'),
      'colors' => [
      'Primary Color' => '#ef2936',
      'Secondary Color' => '#fd7982',
      ],
    ],
    'set_4' => [
      'title' => t('Color Set 4'),
      'colors' => [
      'Primary Color' => '#f8af48',
      'Secondary Color' => '#f6d372',
      ],
    ],
    'set_5' => [
      'title' => t('Color Set 5'),
      'colors' => [
      'Primary Color' => '#014b5f',
      'Secondary Color' => '#59cad1',
      ],
    ],
    'set_6' => [
      'title' => t('Color Set 6'),
      'colors' => [
      'Primary Color' => '#711c82',
      'Secondary Color' => '#d3afda',
      ],
    ],
    'set_7' => [
      'title' => t('Color Set 7'),
      'colors' => [
      'Primary Color' => '#711c82',
      'Secondary Color' => '#ea27bf',
      ],
    ],
    'set_8' => [
      'title' => t('Color Set 8'),
      'colors' => [
      'Primary Color' => '#e6565e',
      'Secondary Color' => '#461215',
      ],
    ],
    'set_9' => [
      'title' => t('Color Set 9'),
      'colors' => [
      'Primary Color' => '#452e65',
      'Secondary Color' => '#937ab9',
      ],
    ],
];